travis: custom cabal-1.20 build

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,2 +1,28 @@
-language: haskell
-ghc: 7.8
+env:
+ - GHCVER=7.8.2
+
+before_install:
+ - sudo add-apt-repository -y ppa:hvr/ghc
+ - sudo apt-get update
+ - sudo apt-get install cabal-install-1.20 ghc-$GHCVER
+ - export PATH=/opt/ghc/$GHCVER/bin:$PATH
+
+install:
+ - cabal-1.20 update
+ - cabal-1.20 sandbox init
+ - cabal install --only-dependencies
+
+script:
+ - cabal-1.20 configure --enable-tests -v2
+ - cabal-1.20 build
+ - cabal-1.20 test
+ - cabal-1.20 sdist
+ - export SRC_TGZ=$(cabal-1.20 info . | awk '{print $2 ".tar.gz";exit}') ;
+   cd dist/;
+   cabal-1.20 sandbox init;
+   if [ -f "$SRC_TGZ" ]; then
+      cabal-1.20 install "$SRC_TGZ";
+   else
+      echo "expected '$SRC_TGZ' not found";
+      exit 1;
+   fi
